spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dejavue
    username: dejavue
    password: 987256123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
